# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.10

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /mnt/d/Facultate/SI/Tema1

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /mnt/d/Facultate/SI/Tema1

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /mnt/d/Facultate/SI/Tema1/CMakeFiles /mnt/d/Facultate/SI/Tema1/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /mnt/d/Facultate/SI/Tema1/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named a

# Build rule for target.
a : cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 a
.PHONY : a

# fast build rule for target.
a/fast:
	$(MAKE) -f CMakeFiles/a.dir/build.make CMakeFiles/a.dir/build
.PHONY : a/fast

#=============================================================================
# Target rules for targets named key_manager

# Build rule for target.
key_manager: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 key_manager
.PHONY : key_manager

# fast build rule for target.
key_manager/fast:
	$(MAKE) -f CMakeFiles/key_manager.dir/build.make CMakeFiles/key_manager.dir/build
.PHONY : key_manager/fast

#=============================================================================
# Target rules for targets named b

# Build rule for target.
b : cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 b
.PHONY : b

# fast build rule for target.
b/fast:
	$(MAKE) -f CMakeFiles/b.dir/build.make CMakeFiles/b.dir/build
.PHONY : b/fast

a.o: a.cpp.o

.PHONY : a.o

# target to build an object file
a.cpp.o:
	$(MAKE) -f CMakeFiles/a.dir/build.make CMakeFiles/a.dir/a.cpp.o
.PHONY : a.cpp.o

a.i: a.cpp.i

.PHONY : a.i

# target to preprocess a source file
a.cpp.i:
	$(MAKE) -f CMakeFiles/a.dir/build.make CMakeFiles/a.dir/a.cpp.i
.PHONY : a.cpp.i

a.s: a.cpp.s

.PHONY : a.s

# target to generate assembly for a file
a.cpp.s:
	$(MAKE) -f CMakeFiles/a.dir/build.make CMakeFiles/a.dir/a.cpp.s
.PHONY : a.cpp.s

b.o: b.cpp.o

.PHONY : b.o

# target to build an object file
b.cpp.o:
	$(MAKE) -f CMakeFiles/b.dir/build.make CMakeFiles/b.dir/b.cpp.o
.PHONY : b.cpp.o

b.i: b.cpp.i

.PHONY : b.i

# target to preprocess a source file
b.cpp.i:
	$(MAKE) -f CMakeFiles/b.dir/build.make CMakeFiles/b.dir/b.cpp.i
.PHONY : b.cpp.i

b.s: b.cpp.s

.PHONY : b.s

# target to generate assembly for a file
b.cpp.s:
	$(MAKE) -f CMakeFiles/b.dir/build.make CMakeFiles/b.dir/b.cpp.s
.PHONY : b.cpp.s

key_manager.o: key_manager.cpp.o

.PHONY : key_manager.o

# target to build an object file
key_manager.cpp.o:
	$(MAKE) -f CMakeFiles/key_manager.dir/build.make CMakeFiles/key_manager.dir/key_manager.cpp.o
.PHONY : key_manager.cpp.o

key_manager.i: key_manager.cpp.i

.PHONY : key_manager.i

# target to preprocess a source file
key_manager.cpp.i:
	$(MAKE) -f CMakeFiles/key_manager.dir/build.make CMakeFiles/key_manager.dir/key_manager.cpp.i
.PHONY : key_manager.cpp.i

key_manager.s: key_manager.cpp.s

.PHONY : key_manager.s

# target to generate assembly for a file
key_manager.cpp.s:
	$(MAKE) -f CMakeFiles/key_manager.dir/build.make CMakeFiles/key_manager.dir/key_manager.cpp.s
.PHONY : key_manager.cpp.s

message_crypt.o: message_crypt.cpp.o

.PHONY : message_crypt.o

# target to build an object file
message_crypt.cpp.o:
	$(MAKE) -f CMakeFiles/a.dir/build.make CMakeFiles/a.dir/message_crypt.cpp.o
	$(MAKE) -f CMakeFiles/key_manager.dir/build.make CMakeFiles/key_manager.dir/message_crypt.cpp.o
	$(MAKE) -f CMakeFiles/b.dir/build.make CMakeFiles/b.dir/message_crypt.cpp.o
.PHONY : message_crypt.cpp.o

message_crypt.i: message_crypt.cpp.i

.PHONY : message_crypt.i

# target to preprocess a source file
message_crypt.cpp.i:
	$(MAKE) -f CMakeFiles/a.dir/build.make CMakeFiles/a.dir/message_crypt.cpp.i
	$(MAKE) -f CMakeFiles/key_manager.dir/build.make CMakeFiles/key_manager.dir/message_crypt.cpp.i
	$(MAKE) -f CMakeFiles/b.dir/build.make CMakeFiles/b.dir/message_crypt.cpp.i
.PHONY : message_crypt.cpp.i

message_crypt.s: message_crypt.cpp.s

.PHONY : message_crypt.s

# target to generate assembly for a file
message_crypt.cpp.s:
	$(MAKE) -f CMakeFiles/a.dir/build.make CMakeFiles/a.dir/message_crypt.cpp.s
	$(MAKE) -f CMakeFiles/key_manager.dir/build.make CMakeFiles/key_manager.dir/message_crypt.cpp.s
	$(MAKE) -f CMakeFiles/b.dir/build.make CMakeFiles/b.dir/message_crypt.cpp.s
.PHONY : message_crypt.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... a"
	@echo "... key_manager"
	@echo "... b"
	@echo "... a.o"
	@echo "... a.i"
	@echo "... a.s"
	@echo "... b.o"
	@echo "... b.i"
	@echo "... b.s"
	@echo "... key_manager.o"
	@echo "... key_manager.i"
	@echo "... key_manager.s"
	@echo "... message_crypt.o"
	@echo "... message_crypt.i"
	@echo "... message_crypt.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

